{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fmodern\fcharset0 CourierNewPSMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;\red255\green255\blue255;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl280\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 runtime: php55\
api_version: 1\
\
handlers:\
- url: /\
  script: asama1.php\
\
- url: /asama1\
  script: asama1.php\
\
- url: /index\\.html\
  script: asama1.php\
\
\pard\pardeftab720\sl300\partightenfactor0

\f1\fs26 \AppleTypeServices\AppleTypeServicesF65539 \cf3 \strokec4 - url: /asama2\
  script: asama2.php\
\
- url: /asama3\
  script: asama3.php\cf4 \
}